### ISSUE TITLE
PSA+DeepLabV1 or IRN+DeepLabV2?

### ISSUE THREAD

**Issue by guangpintao** [KAIST-vilab/AEFT#1]
The PSA+DeepLabV1 used in the subsequent seed refine and semantic segmentation, have you tried to compare IRN+DeepLabV2?Is PSA+DeepLabV1 a better choice?

**Comment by yoon307** [comment]
For the seed refinement, we used PSA+DeeplabV2 (res38 backbone). Since we didn't have much time at the time of submission,  we didn't try AEFT with IRN. But, in my experience, IRN is a better option.
