### ISSUE TITLE
Can you share the hyperparameter for COCO?

### ISSUE THREAD

**Issue by mongeoroo** [KAIST-vilab/AEFT#4]
Thank you for your great work and share!

However, I want to implement your code on COCO dataset.

Do you use hyperparameters the same as VOC in COCO training session?

If not, can you share your code or hyperparameters?

Thanks

**Comment by yoon307** [comment]
For the weighting parameter lambda, it is the same (1,0.15,0.15) as PASCAL. For the other parameter, refer https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136890323-supp.pdf . Thank you for your interest in our research!
