### ISSUE TITLE
mxnet can not load the pre-trained weight

### ISSUE THREAD

**Issue by Lin-7** [KAIST-vilab/AEFT#7]
I installed the dependencies according to the yaml file you privide and downloaded the specified pre-trained weight file ('resnet_38d.params' file under the 'https://drive.google.com/drive/folders/1Ak7eAs8Y8ujjv8TKIp-qCW20fgiIWTc2' link), but when I ran the code, an error occurred(The error code is 'save_dict = mxnet.nd.load(filename)'. The Error is 'MXNetError: Check failed: fi->Read(data): Invalid NDArray file format').
![1704250938962](https://github.com/KAIST-vilab/AEFT/assets/45335247/db05bd88-54e7-487f-956b-f050a54a1a68)
![1704250938971](https://github.com/KAIST-vilab/AEFT/assets/45335247/20b43682-2c5c-46f5-9af3-52f6931449f1)
![1704250938976](https://github.com/KAIST-vilab/AEFT/assets/45335247/24ea289a-0986-49ee-aa56-1e49696f6bda)

The result of online query shows that it may be because the mxnet library versions when saving weights and roading weights are different, or it may be because the weight file is damaged. I need your help to confirm whether the mxnet version specified by yaml dependent files and the weight file provided in google drive can make the weights load normally.  Thank you!

**Comment by sangrockEG** [comment]
Sorry about the issue, and thank you for the notification.
I just have fixed it.
You can download it now.
